# Generated by Django 5.2 on 2025-06-13 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentikate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this broadcast was created')),
            ],
        ),
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=10000, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentikate.client')),
                ('user', models.ForeignKey(help_text='The user that created this comment', on_delete=django.db.models.deletion.CASCADE, related_name='streamers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(help_text='The type of stream', max_length=50)),
                ('title', models.CharField(help_text='The Title of the Stream', max_length=1000)),
                ('broadcast', models.ForeignKey(blank=True, help_text='The broadcast this stream belongs to, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='bridge.broadcast')),
                ('streamer', models.ForeignKey(help_text='The agent that created this stream', on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='bridge.streamer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('streamer', 'title'), name='Unique stream for agent')],
            },
        ),
        migrations.CreateModel(
            name='CollaborativeBroadcast',
            fields=[
                ('broadcast_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bridge.broadcast')),
                ('title', models.CharField(help_text='The Title of the Broadcast', max_length=1000)),
                ('streamers', models.ManyToManyField(help_text='Users that can collaborate on this broadcast', related_name='collaborative_broadcasts', to='bridge.streamer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('title',), name='Unique broadcast title for collaborative broadcast')],
            },
            bases=('bridge.broadcast',),
        ),
        migrations.CreateModel(
            name='SoloBroadcast',
            fields=[
                ('broadcast_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bridge.broadcast')),
                ('title', models.CharField(help_text='The Title of the Broadcast', max_length=1000)),
                ('streamer', models.ForeignKey(help_text='The agent that created this private broadcast', on_delete=django.db.models.deletion.CASCADE, related_name='solo_broadcasts', to='bridge.streamer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('title', 'streamer'), name='Unique broadcast title for solo broadcast')],
            },
            bases=('bridge.broadcast',),
        ),
    ]
