# Generated by Django 5.2 on 2025-05-09 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentikate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=10000, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentikate.client')),
                ('user', models.ForeignKey(help_text='The user that created this comment', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The Title of the Stream', max_length=1000)),
                ('token', models.CharField(help_text='The token of the stream', max_length=4000)),
                ('agent', models.ForeignKey(help_text='The agent that created this stream', on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='bridge.agent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('agent', 'title'), name='Unique stream for agent')],
            },
        ),
    ]
