# Generated by Django 6.0.6 on 2026-10-09 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('bridge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='The identifier of the object. Consult the documentation for the format', max_length=1000)),
                ('object', models.PositiveIntegerField(help_text='The object id of the object, on its associated service')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('identifier', 'object'), name='Unique structure per identifier and object')],
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the call', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this call was started')),
                ('creator', models.ForeignKey(blank=True, help_text='The user that started this call', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calls', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization this call belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='authentikate.organization')),
                ('about', models.ManyToManyField(blank=True, help_text='The structures this call is about', related_name='calls', to='bridge.structure')),
            ],
        ),
    ]
