# Generated by Django 5.2 on 2025-06-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='app',
            new_name='client',
        ),
    ]
